module ElasticGraph
  class GraphQL
    type resolver = _GraphQLResolverWithLookahead | _GraphQLResolverWithoutLookahead

    module Resolvers
      type graphQLAdapter = ::Hash[::String, untyped]

      class GraphQLAdapterBuilder
        @runtime_metadata: SchemaArtifacts::RuntimeMetadata::Schema
        @resolvers_by_name_and_field_config: ::Hash[::Symbol, ::Hash[::Hash[::Symbol, untyped], resolver]]
        @query_adapter: QueryAdapter
        @use_next_execution_engine: bool

        def initialize: (
          runtime_metadata: SchemaArtifacts::RuntimeMetadata::Schema,
          named_resolvers: namedGraphQLResolversHash,
          query_adapter: QueryAdapter,
          ?use_next_execution_engine: bool
        ) -> void

        def build: () -> ::Hash[::String, untyped]

        private

        def scalar_type_hash: () -> ::Hash[::String, ::Hash[::String, ^(untyped, ::GraphQL::Query::Context) -> untyped]]
        def object_type_hash: () -> ::Hash[::String, ::Hash[::String, ^(untyped, ::Hash[::Symbol, untyped], ::GraphQL::Query::Context) -> untyped]]
        def resolve_type: (::Module, untyped, ::GraphQL::Query::Context) -> untyped
      end
    end
  end
end
