module ElasticGraph
  class GraphQL
    module Resolvers
      module Object
        class WithLookahead
          include _GraphQLResolverWithLookahead
        end

        class WithASTNode
          include _GraphQLResolverWithASTNode
        end

        class WithoutLookahead
          include _GraphQLResolverWithoutLookahead
        end
      end
    end
  end
end
